spring:
  application:
    name: schedule-editor
  http:
    client:
      read-timeout: 300000 #milliseconds
      connect-timeout: 5000 #milliseconds

#const in app
rag:
  folder: rag_documents

save:
  folder: saved_schedules

langchain4j:
  # Google Gemini
  google-ai-gemini:
    chat-model:
      api-key: ${GOOGLE_GEMINI_API_KEY}
      model-name: gemini-2.5-pro-exp-03-25
      temperature: 0.5
  #Ollama
#  ollama:
#    chat-model:
#      base-url: http://localhost:11434
#      model-name: MFDoom/deepseek-r1-tool-calling:1.5b
#      temperature: 0.5
#      timeout: 300000

# Logging
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always

springdoc:
  default-produces-media-type: application/json
logging:
  level:
    dev:
      langchain4j: DEBUG
    org:
      denys:
        hudymov: DEBUG

